// Copyright (c) 2016-2017, Nefeli Networks, Inc.
// All rights reserved.
//
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// * Redistributions of source code must retain the above copyright notice, this
// list of conditions and the following disclaimer.
//
// * Redistributions in binary form must reproduce the above copyright notice,
// this list of conditions and the following disclaimer in the documentation
// and/or other materials provided with the distribution.
//
// * Neither the names of the copyright holders nor the names of their
// contributors may be used to endorse or promote products derived from this
// software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: service.proto

package bess_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\abess.pb\x1a\x0ebess_msg.proto2\xd4\x1b\n" +
	"\vBESSControl\x12?\n" +
	"\n" +
	"GetVersion\x12\x15.bess.pb.EmptyRequest\x1a\x18.bess.pb.VersionResponse\"\x00\x12;\n" +
	"\bResetAll\x12\x15.bess.pb.EmptyRequest\x1a\x16.bess.pb.EmptyResponse\"\x00\x12;\n" +
	"\bKillBess\x12\x15.bess.pb.EmptyRequest\x1a\x16.bess.pb.EmptyResponse\"\x00\x12F\n" +
	"\fImportPlugin\x12\x1c.bess.pb.ImportPluginRequest\x1a\x16.bess.pb.EmptyResponse\"\x00\x12F\n" +
	"\fUnloadPlugin\x12\x1c.bess.pb.UnloadPluginRequest\x1a\x16.bess.pb.EmptyResponse\"\x00\x12D\n" +
	"\vListPlugins\x12\x15.bess.pb.EmptyRequest\x1a\x1c.bess.pb.ListPluginsResponse\"\x00\x12;\n" +
	"\bPauseAll\x12\x15.bess.pb.EmptyRequest\x1a\x16.bess.pb.EmptyResponse\"\x00\x12D\n" +
	"\vPauseWorker\x12\x1b.bess.pb.PauseWorkerRequest\x1a\x16.bess.pb.EmptyResponse\"\x00\x12F\n" +
	"\fResumeWorker\x12\x1c.bess.pb.ResumeWorkerRequest\x1a\x16.bess.pb.EmptyResponse\"\x00\x12<\n" +
	"\tResumeAll\x12\x15.bess.pb.EmptyRequest\x1a\x16.bess.pb.EmptyResponse\"\x00\x12?\n" +
	"\fResetWorkers\x12\x15.bess.pb.EmptyRequest\x1a\x16.bess.pb.EmptyResponse\"\x00\x12D\n" +
	"\vListWorkers\x12\x15.bess.pb.EmptyRequest\x1a\x1c.bess.pb.ListWorkersResponse\"\x00\x12@\n" +
	"\tAddWorker\x12\x19.bess.pb.AddWorkerRequest\x1a\x16.bess.pb.EmptyResponse\"\x00\x12H\n" +
	"\rDestroyWorker\x12\x1d.bess.pb.DestroyWorkerRequest\x1a\x16.bess.pb.EmptyResponse\"\x00\x12;\n" +
	"\bResetTcs\x12\x15.bess.pb.EmptyRequest\x1a\x16.bess.pb.EmptyResponse\"\x00\x12>\n" +
	"\aListTcs\x12\x17.bess.pb.ListTcsRequest\x1a\x18.bess.pb.ListTcsResponse\"\x00\x12b\n" +
	"\x1aCheckSchedulingConstraints\x12\x15.bess.pb.EmptyRequest\x1a+.bess.pb.CheckSchedulingConstraintsResponse\"\x00\x128\n" +
	"\x05AddTc\x12\x15.bess.pb.AddTcRequest\x1a\x16.bess.pb.EmptyResponse\"\x00\x12J\n" +
	"\x0eUpdateTcParams\x12\x1e.bess.pb.UpdateTcParamsRequest\x1a\x16.bess.pb.EmptyResponse\"\x00\x12J\n" +
	"\x0eUpdateTcParent\x12\x1e.bess.pb.UpdateTcParentRequest\x1a\x16.bess.pb.EmptyResponse\"\x00\x12G\n" +
	"\n" +
	"GetTcStats\x12\x1a.bess.pb.GetTcStatsRequest\x1a\x1b.bess.pb.GetTcStatsResponse\"\x00\x12D\n" +
	"\vListDrivers\x12\x15.bess.pb.EmptyRequest\x1a\x1c.bess.pb.ListDriversResponse\"\x00\x12P\n" +
	"\rGetDriverInfo\x12\x1d.bess.pb.GetDriverInfoRequest\x1a\x1e.bess.pb.GetDriverInfoResponse\"\x00\x12=\n" +
	"\n" +
	"ResetPorts\x12\x15.bess.pb.EmptyRequest\x1a\x16.bess.pb.EmptyResponse\"\x00\x12@\n" +
	"\tListPorts\x12\x15.bess.pb.EmptyRequest\x1a\x1a.bess.pb.ListPortsResponse\"\x00\x12G\n" +
	"\n" +
	"CreatePort\x12\x1a.bess.pb.CreatePortRequest\x1a\x1b.bess.pb.CreatePortResponse\"\x00\x12D\n" +
	"\vDestroyPort\x12\x1b.bess.pb.DestroyPortRequest\x1a\x16.bess.pb.EmptyResponse\"\x00\x12F\n" +
	"\vSetPortConf\x12\x1b.bess.pb.SetPortConfRequest\x1a\x18.bess.pb.CommandResponse\"\x00\x12J\n" +
	"\vGetPortConf\x12\x1b.bess.pb.GetPortConfRequest\x1a\x1c.bess.pb.GetPortConfResponse\"\x00\x12M\n" +
	"\fGetPortStats\x12\x1c.bess.pb.GetPortStatsRequest\x1a\x1d.bess.pb.GetPortStatsResponse\"\x00\x12P\n" +
	"\rGetLinkStatus\x12\x1d.bess.pb.GetLinkStatusRequest\x1a\x1e.bess.pb.GetLinkStatusResponse\"\x00\x12B\n" +
	"\n" +
	"ListMclass\x12\x15.bess.pb.EmptyRequest\x1a\x1b.bess.pb.ListMclassResponse\"\x00\x12P\n" +
	"\rGetMclassInfo\x12\x1d.bess.pb.GetMclassInfoRequest\x1a\x1e.bess.pb.GetMclassInfoResponse\"\x00\x12?\n" +
	"\fResetModules\x12\x15.bess.pb.EmptyRequest\x1a\x16.bess.pb.EmptyResponse\"\x00\x12D\n" +
	"\vListModules\x12\x15.bess.pb.EmptyRequest\x1a\x1c.bess.pb.ListModulesResponse\"\x00\x12M\n" +
	"\fCreateModule\x12\x1c.bess.pb.CreateModuleRequest\x1a\x1d.bess.pb.CreateModuleResponse\"\x00\x12H\n" +
	"\rDestroyModule\x12\x1d.bess.pb.DestroyModuleRequest\x1a\x16.bess.pb.EmptyResponse\"\x00\x12P\n" +
	"\rGetModuleInfo\x12\x1d.bess.pb.GetModuleInfoRequest\x1a\x1e.bess.pb.GetModuleInfoResponse\"\x00\x12J\n" +
	"\x0eConnectModules\x12\x1e.bess.pb.ConnectModulesRequest\x1a\x16.bess.pb.EmptyResponse\"\x00\x12P\n" +
	"\x11DisconnectModules\x12!.bess.pb.DisconnectModulesRequest\x1a\x16.bess.pb.EmptyResponse\"\x00\x12J\n" +
	"\vDumpMempool\x12\x1b.bess.pb.DumpMempoolRequest\x1a\x1c.bess.pb.DumpMempoolResponse\"\x00\x12D\n" +
	"\rModuleCommand\x12\x17.bess.pb.CommandRequest\x1a\x18.bess.pb.CommandResponse\"\x00\x12P\n" +
	"\x11ListGateHookClass\x12\x15.bess.pb.EmptyRequest\x1a\".bess.pb.ListGateHookClassResponse\"\x00\x12e\n" +
	"\x14GetGateHookClassInfo\x12$.bess.pb.GetGateHookClassInfoRequest\x1a%.bess.pb.GetGateHookClassInfoResponse\"\x00\x12\\\n" +
	"\x11ConfigureGateHook\x12!.bess.pb.ConfigureGateHookRequest\x1a\".bess.pb.ConfigureGateHookResponse\"\x00\x12H\n" +
	"\rListGateHooks\x12\x15.bess.pb.EmptyRequest\x1a\x1e.bess.pb.ListGateHooksResponse\"\x00\x12N\n" +
	"\x0fGateHookCommand\x12\x1f.bess.pb.GateHookCommandRequest\x1a\x18.bess.pb.CommandResponse\"\x00\x12V\n" +
	"\x13ConfigureResumeHook\x12#.bess.pb.ConfigureResumeHookRequest\x1a\x18.bess.pb.CommandResponse\"\x00B3Z1github.com/omec-project/upf-epc/pfcpiface/bess_pbb\x06proto3"

var file_service_proto_goTypes = []any{
	(*EmptyRequest)(nil),                       // 0: bess.pb.EmptyRequest
	(*ImportPluginRequest)(nil),                // 1: bess.pb.ImportPluginRequest
	(*UnloadPluginRequest)(nil),                // 2: bess.pb.UnloadPluginRequest
	(*PauseWorkerRequest)(nil),                 // 3: bess.pb.PauseWorkerRequest
	(*ResumeWorkerRequest)(nil),                // 4: bess.pb.ResumeWorkerRequest
	(*AddWorkerRequest)(nil),                   // 5: bess.pb.AddWorkerRequest
	(*DestroyWorkerRequest)(nil),               // 6: bess.pb.DestroyWorkerRequest
	(*ListTcsRequest)(nil),                     // 7: bess.pb.ListTcsRequest
	(*AddTcRequest)(nil),                       // 8: bess.pb.AddTcRequest
	(*UpdateTcParamsRequest)(nil),              // 9: bess.pb.UpdateTcParamsRequest
	(*UpdateTcParentRequest)(nil),              // 10: bess.pb.UpdateTcParentRequest
	(*GetTcStatsRequest)(nil),                  // 11: bess.pb.GetTcStatsRequest
	(*GetDriverInfoRequest)(nil),               // 12: bess.pb.GetDriverInfoRequest
	(*CreatePortRequest)(nil),                  // 13: bess.pb.CreatePortRequest
	(*DestroyPortRequest)(nil),                 // 14: bess.pb.DestroyPortRequest
	(*SetPortConfRequest)(nil),                 // 15: bess.pb.SetPortConfRequest
	(*GetPortConfRequest)(nil),                 // 16: bess.pb.GetPortConfRequest
	(*GetPortStatsRequest)(nil),                // 17: bess.pb.GetPortStatsRequest
	(*GetLinkStatusRequest)(nil),               // 18: bess.pb.GetLinkStatusRequest
	(*GetMclassInfoRequest)(nil),               // 19: bess.pb.GetMclassInfoRequest
	(*CreateModuleRequest)(nil),                // 20: bess.pb.CreateModuleRequest
	(*DestroyModuleRequest)(nil),               // 21: bess.pb.DestroyModuleRequest
	(*GetModuleInfoRequest)(nil),               // 22: bess.pb.GetModuleInfoRequest
	(*ConnectModulesRequest)(nil),              // 23: bess.pb.ConnectModulesRequest
	(*DisconnectModulesRequest)(nil),           // 24: bess.pb.DisconnectModulesRequest
	(*DumpMempoolRequest)(nil),                 // 25: bess.pb.DumpMempoolRequest
	(*CommandRequest)(nil),                     // 26: bess.pb.CommandRequest
	(*GetGateHookClassInfoRequest)(nil),        // 27: bess.pb.GetGateHookClassInfoRequest
	(*ConfigureGateHookRequest)(nil),           // 28: bess.pb.ConfigureGateHookRequest
	(*GateHookCommandRequest)(nil),             // 29: bess.pb.GateHookCommandRequest
	(*ConfigureResumeHookRequest)(nil),         // 30: bess.pb.ConfigureResumeHookRequest
	(*VersionResponse)(nil),                    // 31: bess.pb.VersionResponse
	(*EmptyResponse)(nil),                      // 32: bess.pb.EmptyResponse
	(*ListPluginsResponse)(nil),                // 33: bess.pb.ListPluginsResponse
	(*ListWorkersResponse)(nil),                // 34: bess.pb.ListWorkersResponse
	(*ListTcsResponse)(nil),                    // 35: bess.pb.ListTcsResponse
	(*CheckSchedulingConstraintsResponse)(nil), // 36: bess.pb.CheckSchedulingConstraintsResponse
	(*GetTcStatsResponse)(nil),                 // 37: bess.pb.GetTcStatsResponse
	(*ListDriversResponse)(nil),                // 38: bess.pb.ListDriversResponse
	(*GetDriverInfoResponse)(nil),              // 39: bess.pb.GetDriverInfoResponse
	(*ListPortsResponse)(nil),                  // 40: bess.pb.ListPortsResponse
	(*CreatePortResponse)(nil),                 // 41: bess.pb.CreatePortResponse
	(*CommandResponse)(nil),                    // 42: bess.pb.CommandResponse
	(*GetPortConfResponse)(nil),                // 43: bess.pb.GetPortConfResponse
	(*GetPortStatsResponse)(nil),               // 44: bess.pb.GetPortStatsResponse
	(*GetLinkStatusResponse)(nil),              // 45: bess.pb.GetLinkStatusResponse
	(*ListMclassResponse)(nil),                 // 46: bess.pb.ListMclassResponse
	(*GetMclassInfoResponse)(nil),              // 47: bess.pb.GetMclassInfoResponse
	(*ListModulesResponse)(nil),                // 48: bess.pb.ListModulesResponse
	(*CreateModuleResponse)(nil),               // 49: bess.pb.CreateModuleResponse
	(*GetModuleInfoResponse)(nil),              // 50: bess.pb.GetModuleInfoResponse
	(*DumpMempoolResponse)(nil),                // 51: bess.pb.DumpMempoolResponse
	(*ListGateHookClassResponse)(nil),          // 52: bess.pb.ListGateHookClassResponse
	(*GetGateHookClassInfoResponse)(nil),       // 53: bess.pb.GetGateHookClassInfoResponse
	(*ConfigureGateHookResponse)(nil),          // 54: bess.pb.ConfigureGateHookResponse
	(*ListGateHooksResponse)(nil),              // 55: bess.pb.ListGateHooksResponse
}
var file_service_proto_depIdxs = []int32{
	0,  // 0: bess.pb.BESSControl.GetVersion:input_type -> bess.pb.EmptyRequest
	0,  // 1: bess.pb.BESSControl.ResetAll:input_type -> bess.pb.EmptyRequest
	0,  // 2: bess.pb.BESSControl.KillBess:input_type -> bess.pb.EmptyRequest
	1,  // 3: bess.pb.BESSControl.ImportPlugin:input_type -> bess.pb.ImportPluginRequest
	2,  // 4: bess.pb.BESSControl.UnloadPlugin:input_type -> bess.pb.UnloadPluginRequest
	0,  // 5: bess.pb.BESSControl.ListPlugins:input_type -> bess.pb.EmptyRequest
	0,  // 6: bess.pb.BESSControl.PauseAll:input_type -> bess.pb.EmptyRequest
	3,  // 7: bess.pb.BESSControl.PauseWorker:input_type -> bess.pb.PauseWorkerRequest
	4,  // 8: bess.pb.BESSControl.ResumeWorker:input_type -> bess.pb.ResumeWorkerRequest
	0,  // 9: bess.pb.BESSControl.ResumeAll:input_type -> bess.pb.EmptyRequest
	0,  // 10: bess.pb.BESSControl.ResetWorkers:input_type -> bess.pb.EmptyRequest
	0,  // 11: bess.pb.BESSControl.ListWorkers:input_type -> bess.pb.EmptyRequest
	5,  // 12: bess.pb.BESSControl.AddWorker:input_type -> bess.pb.AddWorkerRequest
	6,  // 13: bess.pb.BESSControl.DestroyWorker:input_type -> bess.pb.DestroyWorkerRequest
	0,  // 14: bess.pb.BESSControl.ResetTcs:input_type -> bess.pb.EmptyRequest
	7,  // 15: bess.pb.BESSControl.ListTcs:input_type -> bess.pb.ListTcsRequest
	0,  // 16: bess.pb.BESSControl.CheckSchedulingConstraints:input_type -> bess.pb.EmptyRequest
	8,  // 17: bess.pb.BESSControl.AddTc:input_type -> bess.pb.AddTcRequest
	9,  // 18: bess.pb.BESSControl.UpdateTcParams:input_type -> bess.pb.UpdateTcParamsRequest
	10, // 19: bess.pb.BESSControl.UpdateTcParent:input_type -> bess.pb.UpdateTcParentRequest
	11, // 20: bess.pb.BESSControl.GetTcStats:input_type -> bess.pb.GetTcStatsRequest
	0,  // 21: bess.pb.BESSControl.ListDrivers:input_type -> bess.pb.EmptyRequest
	12, // 22: bess.pb.BESSControl.GetDriverInfo:input_type -> bess.pb.GetDriverInfoRequest
	0,  // 23: bess.pb.BESSControl.ResetPorts:input_type -> bess.pb.EmptyRequest
	0,  // 24: bess.pb.BESSControl.ListPorts:input_type -> bess.pb.EmptyRequest
	13, // 25: bess.pb.BESSControl.CreatePort:input_type -> bess.pb.CreatePortRequest
	14, // 26: bess.pb.BESSControl.DestroyPort:input_type -> bess.pb.DestroyPortRequest
	15, // 27: bess.pb.BESSControl.SetPortConf:input_type -> bess.pb.SetPortConfRequest
	16, // 28: bess.pb.BESSControl.GetPortConf:input_type -> bess.pb.GetPortConfRequest
	17, // 29: bess.pb.BESSControl.GetPortStats:input_type -> bess.pb.GetPortStatsRequest
	18, // 30: bess.pb.BESSControl.GetLinkStatus:input_type -> bess.pb.GetLinkStatusRequest
	0,  // 31: bess.pb.BESSControl.ListMclass:input_type -> bess.pb.EmptyRequest
	19, // 32: bess.pb.BESSControl.GetMclassInfo:input_type -> bess.pb.GetMclassInfoRequest
	0,  // 33: bess.pb.BESSControl.ResetModules:input_type -> bess.pb.EmptyRequest
	0,  // 34: bess.pb.BESSControl.ListModules:input_type -> bess.pb.EmptyRequest
	20, // 35: bess.pb.BESSControl.CreateModule:input_type -> bess.pb.CreateModuleRequest
	21, // 36: bess.pb.BESSControl.DestroyModule:input_type -> bess.pb.DestroyModuleRequest
	22, // 37: bess.pb.BESSControl.GetModuleInfo:input_type -> bess.pb.GetModuleInfoRequest
	23, // 38: bess.pb.BESSControl.ConnectModules:input_type -> bess.pb.ConnectModulesRequest
	24, // 39: bess.pb.BESSControl.DisconnectModules:input_type -> bess.pb.DisconnectModulesRequest
	25, // 40: bess.pb.BESSControl.DumpMempool:input_type -> bess.pb.DumpMempoolRequest
	26, // 41: bess.pb.BESSControl.ModuleCommand:input_type -> bess.pb.CommandRequest
	0,  // 42: bess.pb.BESSControl.ListGateHookClass:input_type -> bess.pb.EmptyRequest
	27, // 43: bess.pb.BESSControl.GetGateHookClassInfo:input_type -> bess.pb.GetGateHookClassInfoRequest
	28, // 44: bess.pb.BESSControl.ConfigureGateHook:input_type -> bess.pb.ConfigureGateHookRequest
	0,  // 45: bess.pb.BESSControl.ListGateHooks:input_type -> bess.pb.EmptyRequest
	29, // 46: bess.pb.BESSControl.GateHookCommand:input_type -> bess.pb.GateHookCommandRequest
	30, // 47: bess.pb.BESSControl.ConfigureResumeHook:input_type -> bess.pb.ConfigureResumeHookRequest
	31, // 48: bess.pb.BESSControl.GetVersion:output_type -> bess.pb.VersionResponse
	32, // 49: bess.pb.BESSControl.ResetAll:output_type -> bess.pb.EmptyResponse
	32, // 50: bess.pb.BESSControl.KillBess:output_type -> bess.pb.EmptyResponse
	32, // 51: bess.pb.BESSControl.ImportPlugin:output_type -> bess.pb.EmptyResponse
	32, // 52: bess.pb.BESSControl.UnloadPlugin:output_type -> bess.pb.EmptyResponse
	33, // 53: bess.pb.BESSControl.ListPlugins:output_type -> bess.pb.ListPluginsResponse
	32, // 54: bess.pb.BESSControl.PauseAll:output_type -> bess.pb.EmptyResponse
	32, // 55: bess.pb.BESSControl.PauseWorker:output_type -> bess.pb.EmptyResponse
	32, // 56: bess.pb.BESSControl.ResumeWorker:output_type -> bess.pb.EmptyResponse
	32, // 57: bess.pb.BESSControl.ResumeAll:output_type -> bess.pb.EmptyResponse
	32, // 58: bess.pb.BESSControl.ResetWorkers:output_type -> bess.pb.EmptyResponse
	34, // 59: bess.pb.BESSControl.ListWorkers:output_type -> bess.pb.ListWorkersResponse
	32, // 60: bess.pb.BESSControl.AddWorker:output_type -> bess.pb.EmptyResponse
	32, // 61: bess.pb.BESSControl.DestroyWorker:output_type -> bess.pb.EmptyResponse
	32, // 62: bess.pb.BESSControl.ResetTcs:output_type -> bess.pb.EmptyResponse
	35, // 63: bess.pb.BESSControl.ListTcs:output_type -> bess.pb.ListTcsResponse
	36, // 64: bess.pb.BESSControl.CheckSchedulingConstraints:output_type -> bess.pb.CheckSchedulingConstraintsResponse
	32, // 65: bess.pb.BESSControl.AddTc:output_type -> bess.pb.EmptyResponse
	32, // 66: bess.pb.BESSControl.UpdateTcParams:output_type -> bess.pb.EmptyResponse
	32, // 67: bess.pb.BESSControl.UpdateTcParent:output_type -> bess.pb.EmptyResponse
	37, // 68: bess.pb.BESSControl.GetTcStats:output_type -> bess.pb.GetTcStatsResponse
	38, // 69: bess.pb.BESSControl.ListDrivers:output_type -> bess.pb.ListDriversResponse
	39, // 70: bess.pb.BESSControl.GetDriverInfo:output_type -> bess.pb.GetDriverInfoResponse
	32, // 71: bess.pb.BESSControl.ResetPorts:output_type -> bess.pb.EmptyResponse
	40, // 72: bess.pb.BESSControl.ListPorts:output_type -> bess.pb.ListPortsResponse
	41, // 73: bess.pb.BESSControl.CreatePort:output_type -> bess.pb.CreatePortResponse
	32, // 74: bess.pb.BESSControl.DestroyPort:output_type -> bess.pb.EmptyResponse
	42, // 75: bess.pb.BESSControl.SetPortConf:output_type -> bess.pb.CommandResponse
	43, // 76: bess.pb.BESSControl.GetPortConf:output_type -> bess.pb.GetPortConfResponse
	44, // 77: bess.pb.BESSControl.GetPortStats:output_type -> bess.pb.GetPortStatsResponse
	45, // 78: bess.pb.BESSControl.GetLinkStatus:output_type -> bess.pb.GetLinkStatusResponse
	46, // 79: bess.pb.BESSControl.ListMclass:output_type -> bess.pb.ListMclassResponse
	47, // 80: bess.pb.BESSControl.GetMclassInfo:output_type -> bess.pb.GetMclassInfoResponse
	32, // 81: bess.pb.BESSControl.ResetModules:output_type -> bess.pb.EmptyResponse
	48, // 82: bess.pb.BESSControl.ListModules:output_type -> bess.pb.ListModulesResponse
	49, // 83: bess.pb.BESSControl.CreateModule:output_type -> bess.pb.CreateModuleResponse
	32, // 84: bess.pb.BESSControl.DestroyModule:output_type -> bess.pb.EmptyResponse
	50, // 85: bess.pb.BESSControl.GetModuleInfo:output_type -> bess.pb.GetModuleInfoResponse
	32, // 86: bess.pb.BESSControl.ConnectModules:output_type -> bess.pb.EmptyResponse
	32, // 87: bess.pb.BESSControl.DisconnectModules:output_type -> bess.pb.EmptyResponse
	51, // 88: bess.pb.BESSControl.DumpMempool:output_type -> bess.pb.DumpMempoolResponse
	42, // 89: bess.pb.BESSControl.ModuleCommand:output_type -> bess.pb.CommandResponse
	52, // 90: bess.pb.BESSControl.ListGateHookClass:output_type -> bess.pb.ListGateHookClassResponse
	53, // 91: bess.pb.BESSControl.GetGateHookClassInfo:output_type -> bess.pb.GetGateHookClassInfoResponse
	54, // 92: bess.pb.BESSControl.ConfigureGateHook:output_type -> bess.pb.ConfigureGateHookResponse
	55, // 93: bess.pb.BESSControl.ListGateHooks:output_type -> bess.pb.ListGateHooksResponse
	42, // 94: bess.pb.BESSControl.GateHookCommand:output_type -> bess.pb.CommandResponse
	42, // 95: bess.pb.BESSControl.ConfigureResumeHook:output_type -> bess.pb.CommandResponse
	48, // [48:96] is the sub-list for method output_type
	0,  // [0:48] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_bess_msg_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
