# SPDX-FileCopyrightText: 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

repos:
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.30.1
  hooks:
  - id: gitleaks
- repo: https://github.com/golangci/golangci-lint
  rev: v2.11.3
  hooks:
  - id: golangci-lint
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
    args:
    - --markdown-linebreak-ext=md
- repo: https://codeberg.org/fsfe/reuse-tool
  rev: v6.2.0
  hooks:
  - id: reuse
- repo: local
  hooks:
  - id: go-test
    name: go test
    entry: go test ./... -count=1
    language: system
    pass_filenames: false
  # - id: staticcheck
  #   name: staticcheck
  #   entry: staticcheck ./...
  #   language: golang
  #   additional_dependencies:
  #   - honnef.co/go/tools/cmd/staticcheck@v0.7.0
  #   pass_filenames: false
