{
 "title": "OMEC User Plane Custom",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "site",
    "label": "Site",
    "query": "label_values(kube_pod_info, datacenter)"
   },
   {
    "name": "pctile",
    "label": "Percentile",
    "query": "50, 75, 90, 95, 99, 99.9, 99.99, 99.999, 99.9999, 100"
   }
  ]
 },
 "panels": [
  {
   "title": "UPF Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "upf_latency_ns{datacenter=\"$site\",quantile=~\"$pctile\"}",
     "legendFormat": " {{instance}} | {{ iface }} | {{ quantile }}"
    }
   ]
  },
  {
   "title": "UPF Jitter",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "upf_jitter_ns{datacenter=\"$site\",quantile=~\"$pctile\"}",
     "legendFormat": " {{instance}} | {{ iface }} | {{ quantile }}"
    }
   ]
  },
  {
   "title": "UPF Packet Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "upf_packets_count{datacenter=\"$site\"}",
     "legendFormat": "{{dir}}: {{instance}} | {{ iface }} "
    }
   ]
  },
  {
   "title": "UPF Byte Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "upf_bytes_count{datacenter=\"$site\"}",
     "legendFormat": "{{dir}}: {{instance}} | {{ iface }}"
    }
   ]
  },
  {
   "title": "UPF Dropped Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "upf_dropped_count{datacenter=\"$site\"}",
     "legendFormat": "{{dir}}: {{instance}} | {{ iface }}"
    }
   ]
  }
 ]
}