apiVersion: v1
kind: Pod
metadata:
  name: bess
  annotations:
      k8s.v1.cni.cncf.io/networks: '[
            { "name": "s1u-net", "interface": "s1u" },
            { "name": "sgi-net", "interface": "sgi" }
    ]'
spec:
  shareProcessNamespace: true
  # Reqd. if working with AF_PACKET so that kernel does not reply to GTP-U packets
  #initContainers:
  #- name: iptables
  #  image: krsna1729/spgwu
  #  command: [ "sh", "-xec"]
  #  securityContext:
  #    capabilities:
  #      add:
  #        - NET_ADMIN
  #  args:
  #  - iptables -I OUTPUT -p icmp --icmp-type port-unreachable -j DROP;
  containers:
  - name: bess
    image: krsna1729/spgwu
    stdin: true
    tty: true
    args:
      - -grpc-url=0.0.0.0:10514
    livenessProbe:
      tcpSocket:
        port: 10514
      initialDelaySeconds: 15
      periodSeconds: 20
    lifecycle:
      postStart:
        exec:
          command: ["sh", "-c", "until bessctl run spgwu; do sleep 2; done;"]
    securityContext:
      capabilities:
        add:
          - IPC_LOCK # AF_PACKET vdev uses mmap
    resources:
      limits:
        hugepages-1Gi: 2Gi
        cpu: 2
        memory: 256Mi
        intel.com/sriov_vfio: '1'
    volumeMounts:
    - name: bess-conf
      mountPath: /conf
    - name: hugepages
      mountPath: /dev/hugepages
  - name: bess-routectl
    image: krsna1729/spgwu
    command: ["/route_control.py"]
    args:
    - -i
    - s1u
    - sgi
    resources:
      limits:
        cpu: 256m
        memory: 128Mi
    volumeMounts:
    - name: bess-conf
      mountPath: /route_control.py
      subpath: route_control.py
  - name: bess-web
    image: krsna1729/spgwu
    command: ["bessctl"]
    args:
    - http
    - 0.0.0.0
    - '8000'
    resources:
      limits:
        cpu: 256m
        memory: 128Mi
  volumes:
  - name: bess-conf
    configMap:
      name: spgwu-conf
  - name: hugepages
    emptyDir:
      medium: HugePages
