# SPDX-License-Identifier: Apache-2.0
# Copyright 2020-present Open Networking Foundation

# build ptf docker image
build: 
	docker build -t bess-upf-ptf .

clean:
	rm -v lib/*pb2*
	rm -rvf lib/ports/
