# SPDX-FileCopyrightText: Copyright 2020-present Open Networking Foundation.
# SPDX-License-Identifier: Apache-2.0

- version: 2
  port_limit: 2
  interfaces: ['b1:00.0', 'b1:00.1']
  port_bandwidth_gb: 10
  c: 2
  port_info:
    - src_mac: b4:96:91:b4:44:b0
      dest_mac: b4:96:91:b4:47:b8
    - src_mac: b4:96:91:b4:44:b1
      dest_mac: b4:96:91:b4:47:b9
  memory:
    mbuf_64     : 1024
    mbuf_128    : 512
    mbuf_256    : 256
    mbuf_512    : 128
    mbuf_1024   : 256
    mbuf_2048   : 128
    traffic_mbuf_64     : 1024
    traffic_mbuf_128    : 512
    traffic_mbuf_256    : 256
    traffic_mbuf_512    : 128
    traffic_mbuf_1024   : 256
    traffic_mbuf_2048   : 128
    dp_flows    : 4096
  platform:
    master_thread_id: 36
    rx_thread_id: 37  # replaces latency_thread_id
    dual_if:
      - socket: 1
        threads: [38, 39]
