{
 "title": "GTPu Path Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "label_values(kube_pod_info, datacenter)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GTPu Latency (Mean)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expr": "upf_gtpulatencymean_ns{}", "legendFormat": "{{ipAddress}}" }
   ]
  },
  {
   "title": "GTPu Packet Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "upf_gtpupackets_count{datacenter=\"$site\"}",
     "legendFormat": "{{ipAddress}}"
    }
   ]
  },
  {
   "title": "GTPu Latency (Min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expr": "upf_gtpulatencymin_ns{}", "legendFormat": "{{ipAddress}}" }
   ]
  },
  {
   "title": "GTPu Latency (Max)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expr": "upf_gtpulatencymax_ns{}", "legendFormat": "{{ipAddress}}" }
   ]
  }
 ]
}