{
 "title": "UPF Session Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "fseid", "query": { "query": "label_values(fseid)" } },
   { "name": "pdr", "query": { "query": "label_values(pdr)" } },
   {
    "name": "quantile",
    "query": {
     "query": "label_values(upf_session_latency_ns, quantile)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "UPF Session Throughput bps",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "upf_session_throughput_bps{fseid=~\"$fseid\", pdr=~\"$pdr\"}"
    }
   ]
  },
  {
   "title": "UPF Session Throughput pps",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "upf_session_throughput_pps{fseid=~\"$fseid\", pdr=~\"$pdr\"}"
    }
   ]
  },
  {
   "title": "UPF Session Drop rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "upf_session_drop_rate{fseid=~\"$fseid\", pdr=~\"$pdr\"}"
    }
   ]
  },
  {
   "title": "UPF Session Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "upf_session_latency_ns{fseid=~\"$fseid\", pdr=~\"$pdr\", quantile=~\"$quantile\"}"
    }
   ]
  },
  {
   "title": "UPF Session Observation Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "upf_session_observation_duration_ns{fseid=~\"$fseid\", pdr=~\"$pdr\"}"
    }
   ]
  }
 ]
}