{
 "title": "UPF Session Metrics Summary",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "fseid", "query": { "query": "label_values(fseid)" } },
   { "name": "pdr", "query": { "query": "label_values(pdr)" } },
   {
    "name": "quantile",
    "query": {
     "query": "label_values(upf_session_latency_ns, quantile)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "UPF Session Bit Rate",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(upf_session_throughput_bps{fseid=~\"$fseid\", pdr=~\"$pdr\"})"
    }
   ]
  },
  {
   "title": "UPF Session Packet Rate",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(upf_session_throughput_pps{fseid=~\"$fseid\", pdr=~\"$pdr\"})"
    }
   ]
  },
  {
   "title": "UPF Session Processing Latency",
   "type": "stat",
   "description": "Pick specific fseid, pdr and quantile values.\nElse it will say No Data",
   "gridPos": { "h": 11, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upf_session_latency_ns{fseid=\"$fseid\", pdr=\"$pdr\", quantile=\"$quantile\"}"
    }
   ]
  },
  {
   "title": "UPF Session Drop Rate",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(upf_session_drop_rate{fseid=~\"$fseid\", pdr=~\"$pdr\"})"
    }
   ]
  },
  {
   "title": "Observation Duration",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(upf_session_observation_duration_ns{fseid=~\"$fseid\", pdr=~\"$pdr\"})"
    }
   ]
  }
 ]
}