- import_playbook: ci.yml
- import_playbook: docker.yml
- import_playbook: runtime.yml

- hosts: all
  tags: dev
  tasks:
    - name: Install recommended packages for developers
      apt: name={{item}} update_cache=yes
      become: true
      with_items:
        - apt-transport-https
        - ca-certificates
        - git
        - gdb
        - linux-tools-common
        - vim
        - lcov
        - python-autopep8
        - graphviz
