// Copyright (c) 2016-2017, Nefeli Networks, Inc.
// Copyright (c) 2020-2022 Intel Corporation.
// All rights reserved.
//
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// * Redistributions of source code must retain the above copyright notice, this
// list of conditions and the following disclaimer.
//
// * Redistributions in binary form must reproduce the above copyright notice,
// this list of conditions and the following disclaimer in the documentation
// and/or other materials provided with the distribution.
//
// * Neither the names of the copyright holders nor the names of their
// contributors may be used to endorse or promote products derived from this
// software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: ports/port_msg.proto

package bess_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PCAPPortArg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dev           string                 `protobuf:"bytes,1,opt,name=dev,proto3" json:"dev,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PCAPPortArg) Reset() {
	*x = PCAPPortArg{}
	mi := &file_ports_port_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PCAPPortArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PCAPPortArg) ProtoMessage() {}

func (x *PCAPPortArg) ProtoReflect() protoreflect.Message {
	mi := &file_ports_port_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PCAPPortArg.ProtoReflect.Descriptor instead.
func (*PCAPPortArg) Descriptor() ([]byte, []int) {
	return file_ports_port_msg_proto_rawDescGZIP(), []int{0}
}

func (x *PCAPPortArg) GetDev() string {
	if x != nil {
		return x.Dev
	}
	return ""
}

type PMDPortArg struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Loopback bool                   `protobuf:"varint,1,opt,name=loopback,proto3" json:"loopback,omitempty"`
	// Types that are valid to be assigned to Port:
	//
	//	*PMDPortArg_PortId
	//	*PMDPortArg_Pci
	//	*PMDPortArg_Vdev
	Port isPMDPortArg_Port `protobuf_oneof:"port"`
	// See http://dpdk.org/doc/dts/test_plans/dual_vlan_test_plan.html
	VlanOffloadRxStrip  bool `protobuf:"varint,5,opt,name=vlan_offload_rx_strip,json=vlanOffloadRxStrip,proto3" json:"vlan_offload_rx_strip,omitempty"`
	VlanOffloadRxFilter bool `protobuf:"varint,6,opt,name=vlan_offload_rx_filter,json=vlanOffloadRxFilter,proto3" json:"vlan_offload_rx_filter,omitempty"`
	VlanOffloadRxQinq   bool `protobuf:"varint,7,opt,name=vlan_offload_rx_qinq,json=vlanOffloadRxQinq,proto3" json:"vlan_offload_rx_qinq,omitempty"`
	// Types that are valid to be assigned to Socket:
	//
	//	*PMDPortArg_SocketId
	Socket          isPMDPortArg_Socket `protobuf_oneof:"socket"`
	PromiscuousMode bool                `protobuf:"varint,9,opt,name=promiscuous_mode,json=promiscuousMode,proto3" json:"promiscuous_mode,omitempty"`
	Hwcksum         bool                `protobuf:"varint,10,opt,name=hwcksum,proto3" json:"hwcksum,omitempty"`
	// N3 -> 3; N6 -> 6; N9 -> 9
	// [3] or [6, 9]
	FlowProfiles  []uint32 `protobuf:"varint,11,rep,packed,name=flow_profiles,json=flowProfiles,proto3" json:"flow_profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PMDPortArg) Reset() {
	*x = PMDPortArg{}
	mi := &file_ports_port_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PMDPortArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PMDPortArg) ProtoMessage() {}

func (x *PMDPortArg) ProtoReflect() protoreflect.Message {
	mi := &file_ports_port_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PMDPortArg.ProtoReflect.Descriptor instead.
func (*PMDPortArg) Descriptor() ([]byte, []int) {
	return file_ports_port_msg_proto_rawDescGZIP(), []int{1}
}

func (x *PMDPortArg) GetLoopback() bool {
	if x != nil {
		return x.Loopback
	}
	return false
}

func (x *PMDPortArg) GetPort() isPMDPortArg_Port {
	if x != nil {
		return x.Port
	}
	return nil
}

func (x *PMDPortArg) GetPortId() uint64 {
	if x != nil {
		if x, ok := x.Port.(*PMDPortArg_PortId); ok {
			return x.PortId
		}
	}
	return 0
}

func (x *PMDPortArg) GetPci() string {
	if x != nil {
		if x, ok := x.Port.(*PMDPortArg_Pci); ok {
			return x.Pci
		}
	}
	return ""
}

func (x *PMDPortArg) GetVdev() string {
	if x != nil {
		if x, ok := x.Port.(*PMDPortArg_Vdev); ok {
			return x.Vdev
		}
	}
	return ""
}

func (x *PMDPortArg) GetVlanOffloadRxStrip() bool {
	if x != nil {
		return x.VlanOffloadRxStrip
	}
	return false
}

func (x *PMDPortArg) GetVlanOffloadRxFilter() bool {
	if x != nil {
		return x.VlanOffloadRxFilter
	}
	return false
}

func (x *PMDPortArg) GetVlanOffloadRxQinq() bool {
	if x != nil {
		return x.VlanOffloadRxQinq
	}
	return false
}

func (x *PMDPortArg) GetSocket() isPMDPortArg_Socket {
	if x != nil {
		return x.Socket
	}
	return nil
}

func (x *PMDPortArg) GetSocketId() int32 {
	if x != nil {
		if x, ok := x.Socket.(*PMDPortArg_SocketId); ok {
			return x.SocketId
		}
	}
	return 0
}

func (x *PMDPortArg) GetPromiscuousMode() bool {
	if x != nil {
		return x.PromiscuousMode
	}
	return false
}

func (x *PMDPortArg) GetHwcksum() bool {
	if x != nil {
		return x.Hwcksum
	}
	return false
}

func (x *PMDPortArg) GetFlowProfiles() []uint32 {
	if x != nil {
		return x.FlowProfiles
	}
	return nil
}

type isPMDPortArg_Port interface {
	isPMDPortArg_Port()
}

type PMDPortArg_PortId struct {
	PortId uint64 `protobuf:"varint,2,opt,name=port_id,json=portId,proto3,oneof"`
}

type PMDPortArg_Pci struct {
	Pci string `protobuf:"bytes,3,opt,name=pci,proto3,oneof"`
}

type PMDPortArg_Vdev struct {
	Vdev string `protobuf:"bytes,4,opt,name=vdev,proto3,oneof"`
}

func (*PMDPortArg_PortId) isPMDPortArg_Port() {}

func (*PMDPortArg_Pci) isPMDPortArg_Port() {}

func (*PMDPortArg_Vdev) isPMDPortArg_Port() {}

type isPMDPortArg_Socket interface {
	isPMDPortArg_Socket()
}

type PMDPortArg_SocketId struct {
	SocketId int32 `protobuf:"varint,8,opt,name=socket_id,json=socketId,proto3,oneof"`
}

func (*PMDPortArg_SocketId) isPMDPortArg_Socket() {}

type UnixSocketPortArg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / Set the first character to "@" in place of \0 for abstract path
	// / See manpage for unix(7).
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// / Minimum RX polling interval for system calls, when *idle*.
	// / Use a negative number for unthrottled polling. If unspecified or 0,
	// / it is set to 50,000 (50 microseconds, or 20k polls per second)
	MinRxIntervalNs int64 `protobuf:"varint,2,opt,name=min_rx_interval_ns,json=minRxIntervalNs,proto3" json:"min_rx_interval_ns,omitempty"`
	// / If set, the port driver will send a confirmation once
	// / the port is connected.  This lets pybess avoid a race during
	// / testing.  See bessctl/test_utils.py for details.
	ConfirmConnect bool `protobuf:"varint,3,opt,name=confirm_connect,json=confirmConnect,proto3" json:"confirm_connect,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UnixSocketPortArg) Reset() {
	*x = UnixSocketPortArg{}
	mi := &file_ports_port_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnixSocketPortArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnixSocketPortArg) ProtoMessage() {}

func (x *UnixSocketPortArg) ProtoReflect() protoreflect.Message {
	mi := &file_ports_port_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnixSocketPortArg.ProtoReflect.Descriptor instead.
func (*UnixSocketPortArg) Descriptor() ([]byte, []int) {
	return file_ports_port_msg_proto_rawDescGZIP(), []int{2}
}

func (x *UnixSocketPortArg) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UnixSocketPortArg) GetMinRxIntervalNs() int64 {
	if x != nil {
		return x.MinRxIntervalNs
	}
	return 0
}

func (x *UnixSocketPortArg) GetConfirmConnect() bool {
	if x != nil {
		return x.ConfirmConnect
	}
	return false
}

type VPortArg struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Ifname string                 `protobuf:"bytes,1,opt,name=ifname,proto3" json:"ifname,omitempty"`
	// Types that are valid to be assigned to Cpid:
	//
	//	*VPortArg_Docker
	//	*VPortArg_ContainerPid
	//	*VPortArg_Netns
	Cpid          isVPortArg_Cpid `protobuf_oneof:"cpid"`
	RxqCpus       []int64         `protobuf:"varint,5,rep,packed,name=rxq_cpus,json=rxqCpus,proto3" json:"rxq_cpus,omitempty"`
	TxTci         uint64          `protobuf:"varint,6,opt,name=tx_tci,json=txTci,proto3" json:"tx_tci,omitempty"`
	TxOuterTci    uint64          `protobuf:"varint,7,opt,name=tx_outer_tci,json=txOuterTci,proto3" json:"tx_outer_tci,omitempty"`
	Loopback      bool            `protobuf:"varint,8,opt,name=loopback,proto3" json:"loopback,omitempty"`
	IpAddrs       []string        `protobuf:"bytes,9,rep,name=ip_addrs,json=ipAddrs,proto3" json:"ip_addrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VPortArg) Reset() {
	*x = VPortArg{}
	mi := &file_ports_port_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VPortArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VPortArg) ProtoMessage() {}

func (x *VPortArg) ProtoReflect() protoreflect.Message {
	mi := &file_ports_port_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VPortArg.ProtoReflect.Descriptor instead.
func (*VPortArg) Descriptor() ([]byte, []int) {
	return file_ports_port_msg_proto_rawDescGZIP(), []int{3}
}

func (x *VPortArg) GetIfname() string {
	if x != nil {
		return x.Ifname
	}
	return ""
}

func (x *VPortArg) GetCpid() isVPortArg_Cpid {
	if x != nil {
		return x.Cpid
	}
	return nil
}

func (x *VPortArg) GetDocker() string {
	if x != nil {
		if x, ok := x.Cpid.(*VPortArg_Docker); ok {
			return x.Docker
		}
	}
	return ""
}

func (x *VPortArg) GetContainerPid() int64 {
	if x != nil {
		if x, ok := x.Cpid.(*VPortArg_ContainerPid); ok {
			return x.ContainerPid
		}
	}
	return 0
}

func (x *VPortArg) GetNetns() string {
	if x != nil {
		if x, ok := x.Cpid.(*VPortArg_Netns); ok {
			return x.Netns
		}
	}
	return ""
}

func (x *VPortArg) GetRxqCpus() []int64 {
	if x != nil {
		return x.RxqCpus
	}
	return nil
}

func (x *VPortArg) GetTxTci() uint64 {
	if x != nil {
		return x.TxTci
	}
	return 0
}

func (x *VPortArg) GetTxOuterTci() uint64 {
	if x != nil {
		return x.TxOuterTci
	}
	return 0
}

func (x *VPortArg) GetLoopback() bool {
	if x != nil {
		return x.Loopback
	}
	return false
}

func (x *VPortArg) GetIpAddrs() []string {
	if x != nil {
		return x.IpAddrs
	}
	return nil
}

type isVPortArg_Cpid interface {
	isVPortArg_Cpid()
}

type VPortArg_Docker struct {
	Docker string `protobuf:"bytes,2,opt,name=docker,proto3,oneof"`
}

type VPortArg_ContainerPid struct {
	ContainerPid int64 `protobuf:"varint,3,opt,name=container_pid,json=containerPid,proto3,oneof"`
}

type VPortArg_Netns struct {
	Netns string `protobuf:"bytes,4,opt,name=netns,proto3,oneof"`
}

func (*VPortArg_Docker) isVPortArg_Cpid() {}

func (*VPortArg_ContainerPid) isVPortArg_Cpid() {}

func (*VPortArg_Netns) isVPortArg_Cpid() {}

type CndpPortArg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / CNDP JSONC configuration absolute file path.
	JsoncFile string `protobuf:"bytes,1,opt,name=jsonc_file,json=jsoncFile,proto3" json:"jsonc_file,omitempty"`
	// / lport index.
	LportIndex    uint32 `protobuf:"varint,2,opt,name=lport_index,json=lportIndex,proto3" json:"lport_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CndpPortArg) Reset() {
	*x = CndpPortArg{}
	mi := &file_ports_port_msg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CndpPortArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CndpPortArg) ProtoMessage() {}

func (x *CndpPortArg) ProtoReflect() protoreflect.Message {
	mi := &file_ports_port_msg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CndpPortArg.ProtoReflect.Descriptor instead.
func (*CndpPortArg) Descriptor() ([]byte, []int) {
	return file_ports_port_msg_proto_rawDescGZIP(), []int{4}
}

func (x *CndpPortArg) GetJsoncFile() string {
	if x != nil {
		return x.JsoncFile
	}
	return ""
}

func (x *CndpPortArg) GetLportIndex() uint32 {
	if x != nil {
		return x.LportIndex
	}
	return 0
}

var File_ports_port_msg_proto protoreflect.FileDescriptor

const file_ports_port_msg_proto_rawDesc = "" +
	"\n" +
	"\x14ports/port_msg.proto\x12\abess.pb\"\x1f\n" +
	"\vPCAPPortArg\x12\x10\n" +
	"\x03dev\x18\x01 \x01(\tR\x03dev\"\xa1\x03\n" +
	"\n" +
	"PMDPortArg\x12\x1a\n" +
	"\bloopback\x18\x01 \x01(\bR\bloopback\x12\x19\n" +
	"\aport_id\x18\x02 \x01(\x04H\x00R\x06portId\x12\x12\n" +
	"\x03pci\x18\x03 \x01(\tH\x00R\x03pci\x12\x14\n" +
	"\x04vdev\x18\x04 \x01(\tH\x00R\x04vdev\x121\n" +
	"\x15vlan_offload_rx_strip\x18\x05 \x01(\bR\x12vlanOffloadRxStrip\x123\n" +
	"\x16vlan_offload_rx_filter\x18\x06 \x01(\bR\x13vlanOffloadRxFilter\x12/\n" +
	"\x14vlan_offload_rx_qinq\x18\a \x01(\bR\x11vlanOffloadRxQinq\x12\x1d\n" +
	"\tsocket_id\x18\b \x01(\x05H\x01R\bsocketId\x12)\n" +
	"\x10promiscuous_mode\x18\t \x01(\bR\x0fpromiscuousMode\x12\x18\n" +
	"\ahwcksum\x18\n" +
	" \x01(\bR\ahwcksum\x12#\n" +
	"\rflow_profiles\x18\v \x03(\rR\fflowProfilesB\x06\n" +
	"\x04portB\b\n" +
	"\x06socket\"}\n" +
	"\x11UnixSocketPortArg\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12+\n" +
	"\x12min_rx_interval_ns\x18\x02 \x01(\x03R\x0fminRxIntervalNs\x12'\n" +
	"\x0fconfirm_connect\x18\x03 \x01(\bR\x0econfirmConnect\"\x8e\x02\n" +
	"\bVPortArg\x12\x16\n" +
	"\x06ifname\x18\x01 \x01(\tR\x06ifname\x12\x18\n" +
	"\x06docker\x18\x02 \x01(\tH\x00R\x06docker\x12%\n" +
	"\rcontainer_pid\x18\x03 \x01(\x03H\x00R\fcontainerPid\x12\x16\n" +
	"\x05netns\x18\x04 \x01(\tH\x00R\x05netns\x12\x19\n" +
	"\brxq_cpus\x18\x05 \x03(\x03R\arxqCpus\x12\x15\n" +
	"\x06tx_tci\x18\x06 \x01(\x04R\x05txTci\x12 \n" +
	"\ftx_outer_tci\x18\a \x01(\x04R\n" +
	"txOuterTci\x12\x1a\n" +
	"\bloopback\x18\b \x01(\bR\bloopback\x12\x19\n" +
	"\bip_addrs\x18\t \x03(\tR\aipAddrsB\x06\n" +
	"\x04cpid\"M\n" +
	"\vCndpPortArg\x12\x1d\n" +
	"\n" +
	"jsonc_file\x18\x01 \x01(\tR\tjsoncFile\x12\x1f\n" +
	"\vlport_index\x18\x02 \x01(\rR\n" +
	"lportIndexB3Z1github.com/omec-project/upf-epc/pfcpiface/bess_pbb\x06proto3"

var (
	file_ports_port_msg_proto_rawDescOnce sync.Once
	file_ports_port_msg_proto_rawDescData []byte
)

func file_ports_port_msg_proto_rawDescGZIP() []byte {
	file_ports_port_msg_proto_rawDescOnce.Do(func() {
		file_ports_port_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ports_port_msg_proto_rawDesc), len(file_ports_port_msg_proto_rawDesc)))
	})
	return file_ports_port_msg_proto_rawDescData
}

var file_ports_port_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ports_port_msg_proto_goTypes = []any{
	(*PCAPPortArg)(nil),       // 0: bess.pb.PCAPPortArg
	(*PMDPortArg)(nil),        // 1: bess.pb.PMDPortArg
	(*UnixSocketPortArg)(nil), // 2: bess.pb.UnixSocketPortArg
	(*VPortArg)(nil),          // 3: bess.pb.VPortArg
	(*CndpPortArg)(nil),       // 4: bess.pb.CndpPortArg
}
var file_ports_port_msg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ports_port_msg_proto_init() }
func file_ports_port_msg_proto_init() {
	if File_ports_port_msg_proto != nil {
		return
	}
	file_ports_port_msg_proto_msgTypes[1].OneofWrappers = []any{
		(*PMDPortArg_PortId)(nil),
		(*PMDPortArg_Pci)(nil),
		(*PMDPortArg_Vdev)(nil),
		(*PMDPortArg_SocketId)(nil),
	}
	file_ports_port_msg_proto_msgTypes[3].OneofWrappers = []any{
		(*VPortArg_Docker)(nil),
		(*VPortArg_ContainerPid)(nil),
		(*VPortArg_Netns)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ports_port_msg_proto_rawDesc), len(file_ports_port_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ports_port_msg_proto_goTypes,
		DependencyIndexes: file_ports_port_msg_proto_depIdxs,
		MessageInfos:      file_ports_port_msg_proto_msgTypes,
	}.Build()
	File_ports_port_msg_proto = out.File
	file_ports_port_msg_proto_goTypes = nil
	file_ports_port_msg_proto_depIdxs = nil
}
