# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2017 Nefeli Networks, Inc.
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

