# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ports/port_msg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14ports/port_msg.proto\x12\x07\x62\x65ss.pb\"\x1a\n\x0bPCAPPortArg\x12\x0b\n\x03\x64\x65v\x18\x01 \x01(\t\"\x96\x02\n\nPMDPortArg\x12\x10\n\x08loopback\x18\x01 \x01(\x08\x12\x11\n\x07port_id\x18\x02 \x01(\x04H\x00\x12\r\n\x03pci\x18\x03 \x01(\tH\x00\x12\x0e\n\x04vdev\x18\x04 \x01(\tH\x00\x12\x1d\n\x15vlan_offload_rx_strip\x18\x05 \x01(\x08\x12\x1e\n\x16vlan_offload_rx_filter\x18\x06 \x01(\x08\x12\x1c\n\x14vlan_offload_rx_qinq\x18\x07 \x01(\x08\x12\x13\n\tsocket_id\x18\x08 \x01(\x05H\x01\x12\x18\n\x10promiscuous_mode\x18\t \x01(\x08\x12\x0f\n\x07hwcksum\x18\n \x01(\x08\x12\x15\n\rflow_profiles\x18\x0b \x03(\rB\x06\n\x04portB\x08\n\x06socket\"V\n\x11UnixSocketPortArg\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x1a\n\x12min_rx_interval_ns\x18\x02 \x01(\x03\x12\x17\n\x0f\x63onfirm_connect\x18\x03 \x01(\x08\"\xba\x01\n\x08VPortArg\x12\x0e\n\x06ifname\x18\x01 \x01(\t\x12\x10\n\x06\x64ocker\x18\x02 \x01(\tH\x00\x12\x17\n\rcontainer_pid\x18\x03 \x01(\x03H\x00\x12\x0f\n\x05netns\x18\x04 \x01(\tH\x00\x12\x10\n\x08rxq_cpus\x18\x05 \x03(\x03\x12\x0e\n\x06tx_tci\x18\x06 \x01(\x04\x12\x14\n\x0ctx_outer_tci\x18\x07 \x01(\x04\x12\x10\n\x08loopback\x18\x08 \x01(\x08\x12\x10\n\x08ip_addrs\x18\t \x03(\tB\x06\n\x04\x63pid\"6\n\x0b\x43ndpPortArg\x12\x12\n\njsonc_file\x18\x01 \x01(\t\x12\x13\n\x0blport_index\x18\x02 \x01(\rB3Z1github.com/omec-project/upf-epc/pfcpiface/bess_pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ports.port_msg_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z1github.com/omec-project/upf-epc/pfcpiface/bess_pb'
  _globals['_PCAPPORTARG']._serialized_start=33
  _globals['_PCAPPORTARG']._serialized_end=59
  _globals['_PMDPORTARG']._serialized_start=62
  _globals['_PMDPORTARG']._serialized_end=340
  _globals['_UNIXSOCKETPORTARG']._serialized_start=342
  _globals['_UNIXSOCKETPORTARG']._serialized_end=428
  _globals['_VPORTARG']._serialized_start=431
  _globals['_VPORTARG']._serialized_end=617
  _globals['_CNDPPORTARG']._serialized_start=619
  _globals['_CNDPPORTARG']._serialized_end=673
# @@protoc_insertion_point(module_scope)
