// Copyright (c) 2016-2017, Nefeli Networks, Inc.
// All rights reserved.
//
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// * Redistributions of source code must retain the above copyright notice, this
// list of conditions and the following disclaimer.
//
// * Redistributions in binary form must reproduce the above copyright notice,
// this list of conditions and the following disclaimer in the documentation
// and/or other materials provided with the distribution.
//
// * Neither the names of the copyright holders nor the names of their
// contributors may be used to endorse or promote products derived from this
// software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: util_msg.proto

package bess_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// / The Field message represents one field in a packet -- either stored in
// / metadata or in the packet body.
type Field struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Position:
	//
	//	*Field_AttrName
	//	*Field_Offset
	Position      isField_Position `protobuf_oneof:"position"`
	NumBytes      uint32           `protobuf:"varint,3,opt,name=num_bytes,json=numBytes,proto3" json:"num_bytes,omitempty"` /// The size of the data in bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_util_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_util_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_util_msg_proto_rawDescGZIP(), []int{0}
}

func (x *Field) GetPosition() isField_Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Field) GetAttrName() string {
	if x != nil {
		if x, ok := x.Position.(*Field_AttrName); ok {
			return x.AttrName
		}
	}
	return ""
}

func (x *Field) GetOffset() uint32 {
	if x != nil {
		if x, ok := x.Position.(*Field_Offset); ok {
			return x.Offset
		}
	}
	return 0
}

func (x *Field) GetNumBytes() uint32 {
	if x != nil {
		return x.NumBytes
	}
	return 0
}

type isField_Position interface {
	isField_Position()
}

type Field_AttrName struct {
	AttrName string `protobuf:"bytes,1,opt,name=attr_name,json=attrName,proto3,oneof"` /// The metadata attribute assigned to store the data
}

type Field_Offset struct {
	Offset uint32 `protobuf:"varint,2,opt,name=offset,proto3,oneof"` /// The offset in bytes to store the data into
}

func (*Field_AttrName) isField_Position() {}

func (*Field_Offset) isField_Position() {}

// / The FieldData message encodes a value to insert into a packet; the value can
// / be supplied as either an int or a bytestring.
type FieldData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Encoding:
	//
	//	*FieldData_ValueBin
	//	*FieldData_ValueInt
	Encoding      isFieldData_Encoding `protobuf_oneof:"encoding"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldData) Reset() {
	*x = FieldData{}
	mi := &file_util_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldData) ProtoMessage() {}

func (x *FieldData) ProtoReflect() protoreflect.Message {
	mi := &file_util_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldData.ProtoReflect.Descriptor instead.
func (*FieldData) Descriptor() ([]byte, []int) {
	return file_util_msg_proto_rawDescGZIP(), []int{1}
}

func (x *FieldData) GetEncoding() isFieldData_Encoding {
	if x != nil {
		return x.Encoding
	}
	return nil
}

func (x *FieldData) GetValueBin() []byte {
	if x != nil {
		if x, ok := x.Encoding.(*FieldData_ValueBin); ok {
			return x.ValueBin
		}
	}
	return nil
}

func (x *FieldData) GetValueInt() uint64 {
	if x != nil {
		if x, ok := x.Encoding.(*FieldData_ValueInt); ok {
			return x.ValueInt
		}
	}
	return 0
}

type isFieldData_Encoding interface {
	isFieldData_Encoding()
}

type FieldData_ValueBin struct {
	ValueBin []byte `protobuf:"bytes,1,opt,name=value_bin,json=valueBin,proto3,oneof"` /// The value as a bytestring
}

type FieldData_ValueInt struct {
	ValueInt uint64 `protobuf:"varint,2,opt,name=value_int,json=valueInt,proto3,oneof"` /// The value in integer format
}

func (*FieldData_ValueBin) isFieldData_Encoding() {}

func (*FieldData_ValueInt) isFieldData_Encoding() {}

var File_util_msg_proto protoreflect.FileDescriptor

const file_util_msg_proto_rawDesc = "" +
	"\n" +
	"\x0eutil_msg.proto\x12\abess.pb\"i\n" +
	"\x05Field\x12\x1d\n" +
	"\tattr_name\x18\x01 \x01(\tH\x00R\battrName\x12\x18\n" +
	"\x06offset\x18\x02 \x01(\rH\x00R\x06offset\x12\x1b\n" +
	"\tnum_bytes\x18\x03 \x01(\rR\bnumBytesB\n" +
	"\n" +
	"\bposition\"U\n" +
	"\tFieldData\x12\x1d\n" +
	"\tvalue_bin\x18\x01 \x01(\fH\x00R\bvalueBin\x12\x1d\n" +
	"\tvalue_int\x18\x02 \x01(\x04H\x00R\bvalueIntB\n" +
	"\n" +
	"\bencodingB3Z1github.com/omec-project/upf-epc/pfcpiface/bess_pbb\x06proto3"

var (
	file_util_msg_proto_rawDescOnce sync.Once
	file_util_msg_proto_rawDescData []byte
)

func file_util_msg_proto_rawDescGZIP() []byte {
	file_util_msg_proto_rawDescOnce.Do(func() {
		file_util_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_util_msg_proto_rawDesc), len(file_util_msg_proto_rawDesc)))
	})
	return file_util_msg_proto_rawDescData
}

var file_util_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_util_msg_proto_goTypes = []any{
	(*Field)(nil),     // 0: bess.pb.Field
	(*FieldData)(nil), // 1: bess.pb.FieldData
}
var file_util_msg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_util_msg_proto_init() }
func file_util_msg_proto_init() {
	if File_util_msg_proto != nil {
		return
	}
	file_util_msg_proto_msgTypes[0].OneofWrappers = []any{
		(*Field_AttrName)(nil),
		(*Field_Offset)(nil),
	}
	file_util_msg_proto_msgTypes[1].OneofWrappers = []any{
		(*FieldData_ValueBin)(nil),
		(*FieldData_ValueInt)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_util_msg_proto_rawDesc), len(file_util_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_util_msg_proto_goTypes,
		DependencyIndexes: file_util_msg_proto_depIdxs,
		MessageInfos:      file_util_msg_proto_msgTypes,
	}.Build()
	File_util_msg_proto = out.File
	file_util_msg_proto_goTypes = nil
	file_util_msg_proto_depIdxs = nil
}
