# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: util_msg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eutil_msg.proto\x12\x07\x62\x65ss.pb\"M\n\x05\x46ield\x12\x13\n\tattr_name\x18\x01 \x01(\tH\x00\x12\x10\n\x06offset\x18\x02 \x01(\rH\x00\x12\x11\n\tnum_bytes\x18\x03 \x01(\rB\n\n\x08position\"A\n\tFieldData\x12\x13\n\tvalue_bin\x18\x01 \x01(\x0cH\x00\x12\x13\n\tvalue_int\x18\x02 \x01(\x04H\x00\x42\n\n\x08\x65ncodingB3Z1github.com/omec-project/upf-epc/pfcpiface/bess_pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'util_msg_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z1github.com/omec-project/upf-epc/pfcpiface/bess_pb'
  _globals['_FIELD']._serialized_start=27
  _globals['_FIELD']._serialized_end=104
  _globals['_FIELDDATA']._serialized_start=106
  _globals['_FIELDDATA']._serialized_end=171
# @@protoc_insertion_point(module_scope)
