// Code generated by protoc-gen-go. DO NOT EDIT.
// source: util_msg.proto

package bess_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

/// The Field message represents one field in a packet -- either stored in metadata or in the packet body.
type Field struct {
	// Types that are valid to be assigned to Position:
	//	*Field_AttrName
	//	*Field_Offset
	Position             isField_Position `protobuf_oneof:"position"`
	NumBytes             uint32           `protobuf:"varint,3,opt,name=num_bytes,json=numBytes,proto3" json:"num_bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_13ab78aab20448e2, []int{0}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

type isField_Position interface {
	isField_Position()
}

type Field_AttrName struct {
	AttrName string `protobuf:"bytes,1,opt,name=attr_name,json=attrName,proto3,oneof"`
}

type Field_Offset struct {
	Offset uint32 `protobuf:"varint,2,opt,name=offset,proto3,oneof"`
}

func (*Field_AttrName) isField_Position() {}

func (*Field_Offset) isField_Position() {}

func (m *Field) GetPosition() isField_Position {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Field) GetAttrName() string {
	if x, ok := m.GetPosition().(*Field_AttrName); ok {
		return x.AttrName
	}
	return ""
}

func (m *Field) GetOffset() uint32 {
	if x, ok := m.GetPosition().(*Field_Offset); ok {
		return x.Offset
	}
	return 0
}

func (m *Field) GetNumBytes() uint32 {
	if m != nil {
		return m.NumBytes
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Field) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Field_AttrName)(nil),
		(*Field_Offset)(nil),
	}
}

/// The FieldData message encodes a value to insert into a packet; the value can be supplied as either an int or a bytestring.
type FieldData struct {
	// Types that are valid to be assigned to Encoding:
	//	*FieldData_ValueBin
	//	*FieldData_ValueInt
	Encoding             isFieldData_Encoding `protobuf_oneof:"encoding"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FieldData) Reset()         { *m = FieldData{} }
func (m *FieldData) String() string { return proto.CompactTextString(m) }
func (*FieldData) ProtoMessage()    {}
func (*FieldData) Descriptor() ([]byte, []int) {
	return fileDescriptor_13ab78aab20448e2, []int{1}
}

func (m *FieldData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldData.Unmarshal(m, b)
}
func (m *FieldData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldData.Marshal(b, m, deterministic)
}
func (m *FieldData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldData.Merge(m, src)
}
func (m *FieldData) XXX_Size() int {
	return xxx_messageInfo_FieldData.Size(m)
}
func (m *FieldData) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldData.DiscardUnknown(m)
}

var xxx_messageInfo_FieldData proto.InternalMessageInfo

type isFieldData_Encoding interface {
	isFieldData_Encoding()
}

type FieldData_ValueBin struct {
	ValueBin []byte `protobuf:"bytes,1,opt,name=value_bin,json=valueBin,proto3,oneof"`
}

type FieldData_ValueInt struct {
	ValueInt uint64 `protobuf:"varint,2,opt,name=value_int,json=valueInt,proto3,oneof"`
}

func (*FieldData_ValueBin) isFieldData_Encoding() {}

func (*FieldData_ValueInt) isFieldData_Encoding() {}

func (m *FieldData) GetEncoding() isFieldData_Encoding {
	if m != nil {
		return m.Encoding
	}
	return nil
}

func (m *FieldData) GetValueBin() []byte {
	if x, ok := m.GetEncoding().(*FieldData_ValueBin); ok {
		return x.ValueBin
	}
	return nil
}

func (m *FieldData) GetValueInt() uint64 {
	if x, ok := m.GetEncoding().(*FieldData_ValueInt); ok {
		return x.ValueInt
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*FieldData) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*FieldData_ValueBin)(nil),
		(*FieldData_ValueInt)(nil),
	}
}

func init() {
	proto.RegisterType((*Field)(nil), "bess.pb.Field")
	proto.RegisterType((*FieldData)(nil), "bess.pb.FieldData")
}

func init() { proto.RegisterFile("util_msg.proto", fileDescriptor_13ab78aab20448e2) }

var fileDescriptor_13ab78aab20448e2 = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0xcf, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0x05, 0xf0, 0xad, 0x7f, 0xd6, 0x66, 0x50, 0x0f, 0x39, 0x05, 0x44, 0x58, 0xf6, 0xb4, 0xa7,
	0xbd, 0xf8, 0x0d, 0x8a, 0x48, 0xbd, 0x78, 0x28, 0x78, 0x0e, 0x89, 0x9d, 0x96, 0x81, 0x66, 0x52,
	0x9a, 0x89, 0xe0, 0xb7, 0x97, 0x44, 0xd1, 0xe3, 0x7b, 0x0f, 0xe6, 0xc7, 0xc0, 0x7d, 0x16, 0x5a,
	0x6c, 0x48, 0xf3, 0x79, 0xdd, 0xa2, 0x44, 0x7d, 0xe3, 0x31, 0xa5, 0xf3, 0xea, 0x8f, 0x04, 0xd7,
	0x2f, 0x84, 0xcb, 0xa8, 0x1f, 0x41, 0x39, 0x91, 0xcd, 0xb2, 0x0b, 0x68, 0x9a, 0x43, 0x73, 0x52,
	0xfd, 0x6e, 0x68, 0x4b, 0xf5, 0xe6, 0x02, 0x6a, 0x03, 0xfb, 0x38, 0x4d, 0x09, 0xc5, 0x5c, 0x1c,
	0x9a, 0xd3, 0x5d, 0xbf, 0x1b, 0x7e, 0xb3, 0x7e, 0x00, 0xc5, 0x39, 0x58, 0xff, 0x25, 0x98, 0xcc,
	0x65, 0x19, 0x87, 0x96, 0x73, 0xe8, 0x4a, 0xee, 0x00, 0xda, 0x35, 0x26, 0x12, 0x8a, 0x7c, 0x7c,
	0x07, 0x55, 0xa9, 0x67, 0x27, 0xae, 0x70, 0x9f, 0x6e, 0xc9, 0x68, 0x3d, 0x71, 0xe5, 0x6e, 0x0b,
	0x57, 0xab, 0x8e, 0xf8, 0x7f, 0x26, 0xfe, 0x11, 0xaf, 0xfe, 0xe6, 0x57, 0x96, 0x72, 0x16, 0xf9,
	0x23, 0x8e, 0xc4, 0xb3, 0xdf, 0xd7, 0x8f, 0x9e, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x47, 0xa5,
	0xd3, 0xce, 0xe3, 0x00, 0x00, 0x00,
}
