name: Clang Formatter

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup
      run: |
        wget https://raw.githubusercontent.com/NetSys/bess/master/core/.clang-format
    - name: Clang Code Formatter
      uses: krsna1729/clang-format-action
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
