# Copyright 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Fossa check

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  fossa-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: FOSSA scan
        uses: fossas/fossa-action@main
        with:
          api-key: ${{ secrets.FOSSA_OMEC_ORG_PO }}
