# SPDX-License-Identifier: Apache-2.0
# Copyright 2022-Present Intel Corporation
# Copyright 2025 Canonical Ltd.
name: CI Build & Test Pipeline

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      code: ${{ steps.filter.outputs.code }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: filter
        with:
          filters: |
            code:
              - 'core/**'
              - 'bessctl/**'
              - 'pybess/**'
              - 'protobuf/**'
              - 'build.py'
              - 'deps/**'
              - 'env/*.yml'
              - 'env/*.txt'
              - 'env/Dockerfile'
              - 'sample_plugin/**'

  build:
    needs: changes
    if: needs.changes.outputs.code == 'true'
    runs-on: ubuntu-latest
    env:
      CXX: "ccache g++"
      DEBIAN_FRONTEND: noninteractive
      NEEDRESTART_MODE: a
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Restore ccache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.cache/ccache
          key: ccache-${{ runner.os }}-${{ github.sha }}
          restore-keys: ccache-${{ runner.os }}-

      - name: Setup environment (Hugepages)
        run: |
          sudo sysctl -w vm.nr_hugepages=1024
          sudo mkdir -p /mnt/huge
          sudo mount -t hugetlbfs nodev /mnt/huge

      - name: Setup dependencies using Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
          sudo ansible-playbook env/ci.yml -i "localhost," -c local
          ccache -s

      - name: Build BESS
        env:
          PKG_CONFIG_PATH: /usr/lib/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/lib/x86_64-linux-gnu/pkgconfig
          BESS_LINK_DYNAMIC: "1"
        run: |
          sudo --preserve-env=CXX,PKG_CONFIG_PATH,BESS_LINK_DYNAMIC ./build.py bess
          sudo ./build.py kmod
          sudo ldconfig

      - name: Test BESS
        run: |
          (cd core && ./all_test)
          coverage run -m unittest discover -v
          python3 bessctl/run_module_tests.py
          ccache -s
          bessctl/bessctl daemon stop || true
