# SPDX-License-Identifier: Apache-2.0
# Copyright 2019-present Intel Corporation
# Copyright 2025 Canonical Ltd.
on:
  schedule:
    - cron: "0 0 * * *"
permissions:
  issues: write
  pull-requests: write
  contents: read
jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
      contents: read
      actions: read
    uses: omec-project/.github/.github/workflows/stale-issue.yml@d57b6360a2cc92237c201f2bb9ad58b924ef7082 # v0.0.32
    with:
      days_before_stale: 120
      days_before_close: 15
    secrets: inherit
